version: '3'

services:
  badbankbackend:
    build: 
      context: .
    image: badbankbackend
    ports:
      - 8081:8080
    restart: always
    depends_on:
      - badbankmongo
    volumes:
      - .:/app
    environment:
      - MONGODB_URL=mongodb://badbankmongo:27017

  badbankmongo:
    image: mongo
    restart: always