version: '3'

services:
  backend:
    build: 
      context: .
    image: backend
    ports:
      - 8081:8080
    restart: always
    depends_on:
      - mongo
    volumes:
      - .:/app
    environment:
      - MONGODB_URL=mongodb://mongo:27017

  mongo:
    image: mongo
    restart: always